inso/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired

class PostForm(FlaskForm):
	title = StringField('Verfahrensnummer', validators=[DataRequired()])
	content = TextAreaField('Beschreibung/Notizen', validators=[DataRequired()])
	submit = SubmitField('Verfahren abbonieren')

inso/posts/routes.py
from flask import (render_template, url_for, flash, redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from inso import db
from inso.models import Post
from inso.posts.forms import PostForm


posts = Blueprint('posts', __name__)

@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
	form = PostForm()
	if form.validate_on_submit():
		post = Post(title=form.title.data, content=form.content.data, author=current_user)
		db.session.add(post)
		db.session.commit()
		flash('Your Post has been created!', 'success')
		return redirect(url_for('users.insolvenzen'))
	return render_template('create_post.html', title='New Post', form=form, legend='New Post')


@posts.route("/post/<int:post_id>")
def post(post_id):
	post = Post.query.get_or_404(post_id)
	return render_template('post.html', title=post.title, post=post)


@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
def update_post(post_id):
	post = Post.query.get_or_404(post_id)
	if post.author != current_user:
		abort(403)
	form= PostForm()
	if form.validate_on_submit():
		post.title = form.title.data
		post.content = form.content.data
		db.session.commit()
		flash('Your Post has been updated', 'success')
		return redirect(url_for('posts.post', post_id=post.id))
	elif request.method == 'GET':
		form.title.data = post.title
		form.content.data = post.content
	return render_template('create_post.html', title='Update Post', form=form, legend='Update Post')



@posts.route("/post/<int:post_id>/delete", methods=['POST'])
def delete_post(post_id):
	post = Post.query.get_or_404(post_id)
	if post.author != current_user:
		abort(403)
	db.session.delete(post)
	db.session.commit()
	flash('Your Post has been deleted.', 'danger')
	return redirect(url_for('users.insolvenzen'))

inso/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from inso import db, bcrypt
from inso.models import User, Post
from inso.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                   RequestResetForm, ResetPasswordForm)
from inso.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))
	form = RegistrationForm()
	if form.validate_on_submit():
		hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
		user = User(username=form.username.data, email=form.email.data, password=hashed_password)
		db.session.add(user)
		db.session.commit()
		flash('Ihr Benutzerkonto wurde erstellt! Sie können sich nun anmelden', 'success')
		return redirect(url_for('users.login'))
	return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))
	form = LoginForm()
	if form.validate_on_submit():
		user = User.query.filter_by(email=form.email.data).first()
		if user and bcrypt.check_password_hash(user.password, form.password.data):
			login_user(user, remember=form.remember.data)
			next_page = request.args.get('next')
			return redirect(next_page) if next_page else redirect(url_for('users.insolvenzen'))
		else:
			flash('Anmeldung fehlgeschlagen. Bitte prüfen Sie Email und Passwort.', 'danger')
	return render_template('login.html', title='Login', form=form)


@users.route("/logout")
def logout():
	logout_user()
	return redirect(url_for('main.home'))

@users.route("/insolvenzen")
@login_required
def insolvenzen():
	name = current_user
	page = request.args.get('page', 1, type=int)
	posts = Post.query.filter_by(author=name).order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
	return render_template('insolvenzen.html', posts=posts)

@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
	form = UpdateAccountForm()
	if form.validate_on_submit():
		if form.picture.data:
			picture_file = save_picture(form.picture.data)
			current_user.image_file = picture_file
		current_user.username = form.username.data
		current_user.email = form.email.data
		db.session.commit()
		flash('Ihr Profil wurde aktualisiert!', 'success')
		return redirect(url_for('users.account'))
	elif request.method == 'GET':
		form.username.data = current_user.username
		form.email.data = current_user.email
	image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
	return render_template('account.html', title='Account', image_file=image_file, form=form)


@users.route("/user/<string:username>")
def user_posts(username):
	page = request.args.get('page', 1, type=int)
	user = User.query.filter_by(username=username).first_or_404()
	posts = Post.query.filter_by(author=user)\
	.order_by(Post.date_posted.desc())\
	.paginate(page=page, per_page=5)
	return render_template('user_post.html', posts=posts, user=user)


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))
	form = RequestResetForm()
	if form.validate_on_submit():
		user = User.query.filter_by(email=form.email.data).first()
		send_reset_email(user)
		flash('An email has been sent wit instructions to reset your password', 'info')
		return redirect(url_for('users.login'))
	return render_template('reset_request.html', title='Reset Password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))
	user = User.verify_reset_token(token)
	if user is None:
		flash('That is an invalid or expired token', 'warning')
		return redirect(url_for('users.reset_request'))
	form = ResetPasswordForm()
	if form.validate_on_submit():
		hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
		user.password = hashed_password
		db.session.commit()
		flash('Ihr Passwort wurde aktualisiert! Sie können sich nun anmelden', 'success')
		return redirect(url_for('users.login'))
	return render_template('reset_token.html', title='Reset Password', form=form)

inso/templates/about.html
{% extends "layout.html" %}
{% block content %}

<div class="card-deck">

  <div class="card">
    <img class="card-img-top" src="{{ url_for('static', filename='howto/'+'howto1.png') }}" alt="howto2">
    <div class="card-body">
      <h5 class="card-title">Schritt 1</h5>
      <p class="card-text">Im ersten Schritt wird unter "Register" ein persönlicher Account erstellt.</p>
    </div>
    <div class="card-footer">
      
    </div>
  </div>
  <div class="card">
    <img class="card-img-top" src="{{ url_for('static', filename='howto/'+'howto2.png') }}" alt="howto3">
    <div class="card-body">
      <h5 class="card-title">Schritt 2</h5>
      <p class="card-text">Im zweiten Schritt wird ganz einfach unter "New Post" eine neue Entscheidung aboniert.</p>
    </div>
    <div class="card-footer">
      
    </div>
  </div>
</div>
<p>
<div class="card-deck">
  <div class="card">
    <img class="card-img-top" src="{{ url_for('static', filename='howto/'+'howto3.png') }}" alt="howto3">
    <div class="card-body">
      <h5 class="card-title">Schritt 3</h5>
      <p class="card-text">Daraufhin erhält man unter "Meine Insolvenzen" eine Übersicht aller abbonierter Registernummern.</p>
    </div>
    <div class="card-footer">
    </div>
  </div>
  <div class="card">
    <img class="card-img-top" src="{{ url_for('static', filename='howto/'+'howto4.png') }}" alt="howto3">
    <div class="card-body">
      <h5 class="card-title">Schritt 4</h5>
      <p class="card-text">Sobald es Neuigkeiten hinsichtlich einer Registernummer gibt, bekommt man eine Emailbenachrichtigung mit allen relevanten Dokumenten für das weitere Vorgehen.</p>
    </div>
    <div class="card-footer">
    </div>
  </div>
</div>
{% endblock content %}

inso/templates/account.html
{% extends "layout.html" %}
{% block content %}
	<div class="content-section">
		<div class="media">
			<img class="rounded-circle account-img" src="{{ image_file }}">
			<div class="media-body">
				<h2 class="account-heading">{{ current_user.username }}</h2>
				<p class="text-secondary">{{ current_user.email }}</p>
			</div>
		</div>
		
		<form method="POST" action="" enctype="multipart/form-data">
			{{ form.hidden_tag() }}
			<fieldset class="form-group">
				<legend class="boarder-bottom mb-4">Benutzer-Informationen</legend>
				<div class="form-group">
					{{ form.username.label(class="form-control-label")}}
					{% if form.username.errors %}
						{{ form.username.label(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.username.errors %}
								<span>{{ error }}</span>
							{% endfor%}
						</div>
					{% else %}
						{{ form.username(class="form-control form-control-lg")}}
					{% endif %}
				</div>
				<div class="form-group">
					{{ form.email.label(class="form-control-label")}}
					{% if form.email.errors %}
						{{ form.email.label(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.email.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.email(class="form-control form-control-lg")}}
					{% endif %}
				</div>
				<div class="form-group">
					{{ form.picture.label()}}
					{{ form.picture(class="form-control-file")}}
					{% if form.picture.errors %}
						{% for error in form.picture.errors %}
							<span class="text-danger">{{ error }}</span></br>
						{% endfor %}
					{% endif %}
				</div>
			</fieldset>
			<div class="form-group">
				{{ form.submit(class="btn btn-outline-info")}}
			</div>
		</form>

	</div>
{% endblock content %}

inso/templates/create_post.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
	<form method="POST" action="">
		{{ form.hidden_tag() }}
		<fieldset class="form-group">
			<legend class="boarder-bottom mb-4">Verfahren abbonieren</legend>
			<div class="form-group">
				{{ form.title.label(class="form-control-label")}}
				{% if form.title.errors %}
					{{ form.title.label(class="form-control form-control-lg is-invalid") }}
					<div class="invalid-feedback">
						{% for error in form.title.errors %}
							<span>{{ error }}</span>
						{% endfor%}
					</div>
				{% else %}
					{{ form.title(class="form-control form-control-lg") }}
				{% endif %}
			</div>
			<div class="form-group">
				{{ form.content.label(class="form-control-label")}}
				{% if form.content.errors %}
					{{ form.content.label(class="form-control form-control-lg is-invalid") }}
					<div class="invalid-feedback">
						{% for error in form.content.errors %}
							<span>{{ error }}</span>
						{% endfor%}
					</div>
				{% else %}
					{{ form.content(class="form-control form-control-lg") }}
				{% endif %}
			</div>
		</fieldset>
		<div class="form-group">
			{{ form.submit(class="btn btn-outline-info") }}
		</div>
	</form>
</div>
{% endblock content %}

inso/templates/email_verfahren.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width"/>

    <style type="text/css">
        * { margin: 0; padding: 0; font-size: 100%; font-family: 'Avenir Next', "Helvetica Neue", "Helvetica", Helvetica, Arial, sans-serif; line-height: 1.65; }

        img { max-width: 100%; margin: 0 auto; display: block; }

        body, .body-wrap { width: 100% !important; height: 100%; background: #f8f8f8; }

        a { color: #5f788a; text-decoration: none; }

        a:hover { text-decoration: underline; }

        .text-center { text-align: center; }

        .text-right { text-align: right; }

        .text-left { text-align: left; }

        .button { display: inline-block; color: white; background: #5f788a; border: solid #5f788a; border-width: 10px 20px 8px; font-weight: bold; border-radius: 4px; }

        .button:hover { text-decoration: none; }

        h1, h2, h3, h4, h5, h6 { margin-bottom: 20px; line-height: 1.25; }

        h1 { font-size: 32px; }

        h2 { font-size: 28px; }

        h3 { font-size: 24px; }

        h4 { font-size: 20px; }

        h5 { font-size: 16px; }

        p, ul, ol { font-size: 16px; font-weight: normal; margin-bottom: 20px; }

        .container { display: block !important; clear: both !important; margin: 0 auto !important; max-width: 580px !important; }

        .container table { width: 100% !important; border-collapse: collapse; }

        .container .masthead { padding: 80px 0; background: #5f788a; color: white; }

        .container .masthead h1 { margin: 0 auto !important; max-width: 90%; text-transform: uppercase; }

        .container .content { background: white; padding: 30px 35px; }

        .container .content.footer { background: none; }

        .container .content.footer p { margin-bottom: 0; color: #888; text-align: center; font-size: 14px; }

        .container .content.footer a { color: #888; text-decoration: none; font-weight: bold; }

        .container .content.footer a:hover { text-decoration: underline; }
    </style>

</head>
<body>
<table class="body-wrap">
    <tr>
        <td class="container">

            <!-- Message start -->
            <table>
                <tr>
                    <td align="center" class="masthead">

                        <h1>Neues Verfahren...</h1>

                    </td>
                </tr>
                <tr>
                    <td class="content">

                        <h2>Sehr geehrter Herr (Nachname),</h2>

                        <p>Bei Ihrem abbonierten Verfahren mit der Verfahrensnummer (Verfahrensnummer) gibt es Neuigkeiten! Wir haben Ihnen die neue Bekanntmachung als PDF-Dokument angehängt.</p>

                        <p>Vielen Dank, dass Sie den Insolvenzradar benutzen. Es grüßen Sie ganz herzlich, </p>

                        <p><em>– Niklas & Jasper</em></p>

                    </td>
                </tr>
            </table>

        </td>
    </tr>
    <tr>
        <td class="container">

            <!-- Message start -->
            <table>
                <tr>
                    <td class="content footer" align="center">
                        <p>Gesendet von <a href="#">Insolvenzradar</a>, Hauptstrasse 136, 10827 Berlin</p>
                        <p><a href="mailto:insolvenzradar@gmail.com">insolvenzradar@gmail.com</a> | <a href="https://www.q-labs.io/impressum">Impressum</a></p>
                    </td>
                </tr>
            </table>

        </td>
    </tr>
</table>
</body>
</html>

inso/templates/home.html
{% extends "layout.html" %}
{% block content %}
	<div class="jumbotron">
		<h1>Willkommen!</h1>
		Dies ist eine erste Beta-Version unserer Insolvenzapp.
		Sie können einzelne Insolvenzen abbonieren und sich 
		vollautomatisch informieren lassen, sobald Insolvenzen 
		mit der relevanten Verfahrensnummer veröffentlicht werden.
	</div>
	
{% endblock content %}

inso/templates/impressum.html
{% extends "layout.html" %}
{% block content %}
	<div class="jumbotron">
		<h1>Impressum:</h1>
		<div>
		<p>
		<p>
		Niklas Dehio und Jasper Castell<p>
		Hauptstrasse 136<p>
		10827 Berlin<p>

		Email: inso.app@gmail.com
		<p>
		</div>
	</div>
	
{% endblock content %}

inso/templates/insolvenzen.html
{% extends "layout.html" %}
{% block content %}
	{% for post in posts.items %}
		<article class="media content-section">
			<img class = "rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/'+ post.author.image_file) }}">
			<div class="media-body">
			<div class="article-metadata">
				<a class="mr-2" href="{{url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
				<small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
			</div>
			<h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
			<p class="article-content">{{ post.content }}</p>
			</div>
		</article>
	{% endfor %}
	{% for page_num in posts.iter_pages(left_edge=2, right_edge=2, left_current=2, right_current=3) %}
		{% if page_num %}
			{% if posts.page == page_num %}
			<a class="btn btn-info mb-4" href="{{ url_for('users.insolvenzen', page=page_num) }}">{{ page_num }}</a>
			{% else %}
			<a class="btn btn-outline-info mb-4" href="{{ url_for('users.insolvenzen', page=page_num) }}">{{ page_num }}</a>
			{% endif %}
		{% else %}
		...
		{% endif %}
	{% endfor %}
{% endblock content %}

inso/templates/login.html
{% extends "layout.html" %}
{% block content %}
	<div class="content-section">
		<form method="POST" action="">
			{{ form.hidden_tag() }}
			 <svg id="ryan" viewBox="0 0 120 120" xmlns="http://www.w3.org/2000/svg">
            <path d="M0,150 C0,65 120,65 120,150" fill="#e0a243" stroke="#000" stroke-width="2.5" />
            <g class="ears">
                <path d="M46,32 L46,30 C46,16 26,16 26,30 L26,32" fill="#e0a243" stroke="#000" stroke-width="2.5" stroke-linecap="round" transform="rotate(-10,38,24)" />
                <path d="M74,32 L74,30 C74,16 94,16 94,30 L94,32" fill="#e0a243" stroke="#000" stroke-width="2.5" stroke-linecap="round" transform="rotate(10,82,24)" />
            </g>
            <circle cx="60" cy="60" r="40" fill="#e0a243" stroke="#000" stroke-width="2.5" />
            <g class="eyes">
                <!-- left eye and eyebrow-->
                <line x1="37" x2="50" y1="46" y2="46" stroke="#000" stroke-width="3" stroke-linecap="round" />
                <circle cx="44" cy="55" r="3" fill="#000" />
                <!-- right eye and eyebrow -->
                <line x1="70" x2="83" y1="46" y2="46" stroke="#000" stroke-width="3" stroke-linecap="round" />
                <circle cx="76" cy="55" r="3" fill="#000" />
            </g>
            <g class="muzzle">
                <path d="M60,66 C58.5,61 49,63 49,69 C49,75 58,77 60,71 M60,66 C61.5,61 71,63 71,69 C71,75 62,77 60,71" fill="#fff" />
                <path d="M60,66 C58.5,61 49,63 49,69 C49,75 58,77 60,71 M60,66 C61.5,61 71,63 71,69 C71,75 62,77 60,71" fill="#fff" stroke="#000" stroke-width="2.5" stroke-linejoin="round" stroke-linecap="round" />
                <polygon points="59,63.5,60,63.4,61,63.5,60,65" fill="#000" stroke="#000" stroke-width="5" stroke-linejoin="round" />
            </g>
            <path d="M40,105 C10,140 110,140 80,105 L80,105 L70,111 L60,105 L50,111 L40,105" fill="#fff" />
</svg>
			<fieldset class="form-group">
				<legend class="boarder-bottom mb-4">Anmelden</legend>
				<div class="form-group">
					{{ form.email.label(class="form-control-label")}}
					{% if form.email.errors %}
						{{ form.email.label(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.email.errors %}
								<span>{{ error }}</span>
							{% endfor%}
						</div>
					{% else %}
						{{ form.email(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				<div class="form-group">
					{{ form.password.label(class="form-control-label")}}
					{% if form.password.errors %}
						{{ form.password.label(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.password.errors %}
								<span>{{ error }}</span>
							{% endfor%}
						</div>
					{% else %}
						{{ form.password(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				<div class="form-check">
					{{ form.remember(class="form-check-input") }}
					{{ form.remember.label(class="form-check-label") }}
				</div>
			</fieldset>
			<div class="form-group">
				{{ form.submit(class="btn btn-outline-info") }}
				<small class="text-muted ml-2">
					<a href="{{ url_for('users.reset_request') }}">Passwort vergessen?</a>
				</small>
			</div>
		</form>
	</div>
	<div class="border-top pt-3">
		<small class="text-muted">
			Noch nicht registriert? <a class="ml-2" href="{{ url_for('users.register') }}">Jetzt anmelden!</a>
		</small>
	</div>
	<script src="{{ url_for('static', filename='script.js') }}"></script>
{% endblock content %}

inso/templates/post.html
{% extends "layout.html" %}
{% block content %}
<article class="media content-section">
	<img class = "rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/'+ post.author.image_file) }}">
	<div class="media-body">
	<div class="article-metadata">
		<a class="mr-2" href="{{url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
		<small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
		{% if post.author == current_user %}
			<div>
				<a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('posts.update_post', post_id=post.id) }}">Updaten</a>
				<button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Löschen</button>	
				</a>
			</div>
		{% endif %}
	</div>
	<h2 class="article-title">{{ post.title }}</h2>
	<p class="article-content">{{ post.content }}</p>
	</div>
</article>
<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="deleteModalLabel">Verfahren löschen??</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-secondary" data-dismiss="modal">Schließen</button>
				<form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
					<input class="btn btn-danger" type="submit" value="Delete">
				</form>
			</div>
		</div>
	</div>
</div>
{% endblock content %}

inso/templates/register.html
{% extends "layout.html" %}
{% block content %}
	<div class="content-section">
		<form method="POST" action="">
			{{ form.hidden_tag() }}
			<fieldset class="form-group">
				<legend class="boarder-bottom mb-4">Jetzt registrieren!</legend>
				<div class="form-group">
					{{ form.username.label(class="form-control-label")}}
					{% if form.username.errors %}
						{{ form.username.label(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.username.errors %}
								<span>{{ error }}</span>
							{% endfor%}
						</div>
					{% else %}
						{{ form.username(class="form-control form-control-lg")}}
					{% endif %}
				</div>
				<div class="form-group">
					{{ form.email.label(class="form-control-label")}}
					{% if form.email.errors %}
						{{ form.email.label(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.email.errors %}
								<span>{{ error }}</span>
							{% endfor%}
						</div>
					{% else %}
						{{ form.email(class="form-control form-control-lg")}}
					{% endif %}
				</div>
				<div class="form-group">
					{{ form.password.label(class="form-control-label")}}
					{% if form.password.errors %}
						{{ form.password.label(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.password.errors %}
								<span>{{ error }}</span>
							{% endfor%}
						</div>
					{% else %}
						{{ form.password(class="form-control form-control-lg")}}
					{% endif %}
				</div>
				<div class="form-group">
					{{ form.confirm_password.label(class="form-control-label")}}
					{% if form.confirm_password.errors %}
						{{ form.confirm_password.label(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.confirm_password.errors %}
								<span>{{ error }}</span>
							{% endfor%}
						</div>
					{% else %}
						{{ form.confirm_password(class="form-control form-control-lg")}}
					{% endif %}
				</div>
			</fieldset>
			<div class="form-group">
				{{ form.submit(class="btn btn-outline-info")}}
			</div>
		</form>
	</div>
	<div class="border-top pt-3">
		<small class="text-muted">
			Haben Sie bereits einen Account? <a class="ml-2" href="{{ url_for('users.login') }}">Anmelden</a>
		</small>
	</div>
{% endblock content %}

inso/templates/user_post.html
{% extends "layout.html" %}
{% block content %}
	<h1 class="mb-3">Verfahren von {{ user.username }} ({{ posts.total }})</h1>
	{% for post in posts.items %}
		<article class="media content-section">
			<img class = "rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/'+ post.author.image_file) }}">
			<div class="media-body">
			<div class="article-metadata">
				<a class="mr-2" href="{{url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
				<small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
			</div>
			<h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
			<p class="article-content">{{ post.content }}</p>
			</div>
		</article>
	{% endfor %}
	{% for page_num in posts.iter_pages(left_edge=2, right_edge=2, left_current=2, right_current=3) %}
		{% if page_num %}
			{% if posts.page == page_num %}
			<a class="btn btn-info mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
			{% else %}
			<a class="btn btn-outline-info mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
			{% endif %}
		{% else %}
		...
		{% endif %}
	{% endfor %}
{% endblock content %}